fix linux 32-bit build

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -59,25 +59,33 @@ jobs:
           # https://ubuntu.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts
           # https://askubuntu.com/questions/1252062/how-to-install-libncurses-so-5-in-ubuntu-20-04
           # https://askubuntu.com/questions/522372/installing-32-bit-libraries-on-ubuntu-14-04-lts-64-bit
-          # sudo dpkg --add-architecture i386
-          sudo apt update
-          sudo add-apt-repository universe
+          # sudo add-apt-repository universe
           sudo dpkg --add-architecture i386 
           sudo apt update
-          sudo apt upgrade
-          sudo apt install -y \
-            libwebkit2gtk-4.0-dev \
-            build-essential \
-            curl \
-            wget \
-            libssl-dev \
-            libssl-dev:i386 \
-            libgtk-3-dev \
-            patchelf \
-            librsvg2-dev \
-            libappindicator3-dev \
+          # install both 32-bit and 64-bit prerequisites of tauri
+          # libayatana-appindicator3-dev is the successor of libappindicator3-dev and 64-bit only
+          # https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux
+          # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
+          echo FIX INSTALL FAILED ON GITHUB UBUNTU 22.04 RUNNER
+          sudo apt install -y libgcc-s1:i386 libstdc++6:i386 libgdk-pixbuf-2.0-dev:i386 libgdk-pixbuf2.0-dev:i386 libatomic1:i386
+          echo install tools for 32-bit support ...
+          sudo apt install -y --allow-downgrades \
             gcc-multilib \
             g++-multilib
+          echo install 32-bit dependences ...
+          sudo apt install -y --allow-downgrades \
+            libwebkit2gtk-4.0-dev:i386 \
+            libssl-dev:i386 \
+            libgtk-3-dev:i386 \
+            librsvg2-dev:i386 || echo "install 32-bit dependences failed! Check the logs for details."
+          echo install dependences ...
+          sudo apt install -y --allow-downgrades \
+            libwebkit2gtk-4.0-dev \
+            libssl-dev \
+            libgtk-3-dev \
+            librsvg2-dev \
+            libayatana-appindicator3-dev
+          echo 'ok'
       - name: 'Setup for macos'
         if: matrix.os == 'macos-latest'
         run: |
@@ -97,9 +105,9 @@ jobs:
           yarn
           yarn tauri info
           yarn tauri build -t x86_64-unknown-linux-gnu
-          export OPENSSL_LIB_DIR=/usr/lib/i386-linux-gnu/
-          export OPENSSL_INCLUDE_DIR=/usr/include/openssl/
-          yarn tauri build -t i686-unknown-linux-gnu || true
+          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/:$PKG_CONFIG_PATH
+          export PKG_CONFIG_SYSROOT_DIR=/
+          yarn tauri build -t i686-unknown-linux-gnu
           echo "build native binarys finished"
       - name: Build Native binarys on macos
         if: matrix.os == 'macos-latest'
@@ -160,9 +168,14 @@ jobs:
         continue-on-error: true
         if: matrix.os == 'ubuntu-latest'
         run: |
+          # for 64-bit binary
           mv src-tauri/target/x86_64-unknown-linux-gnu/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{steps.branch_name.outputs.PROJECT_VERSION}}_amd64${{matrix.executable_extension}}
           mv src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/appimage/${{env.APP_NAME}}_${{steps.branch_name.outputs.PROJECT_VERSION}}_amd64.AppImage ${{env.APP_NAME}}-${{matrix.label}}-${{steps.branch_name.outputs.PROJECT_VERSION}}_amd64.AppImage
           mv src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/${{env.APP_NAME}}_${{steps.branch_name.outputs.PROJECT_VERSION}}_amd64.deb ${{env.APP_NAME}}-${{matrix.label}}-${{steps.branch_name.outputs.PROJECT_VERSION}}_amd64.deb
+          # for 32-bit binary
+          mv src-tauri/target/i686-unknown-linux-gnu/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{steps.branch_name.outputs.PROJECT_VERSION}}_i386${{matrix.executable_extension}}
+          mv src-tauri/target/i686-unknown-linux-gnu/release/bundle/appimage/${{env.APP_NAME}}_${{steps.branch_name.outputs.PROJECT_VERSION}}_i386.AppImage ${{env.APP_NAME}}-${{matrix.label}}-${{steps.branch_name.outputs.PROJECT_VERSION}}_i386.AppImage
+          mv src-tauri/target/i686-unknown-linux-gnu/release/bundle/deb/${{env.APP_NAME}}_${{steps.branch_name.outputs.PROJECT_VERSION}}_i386.deb ${{env.APP_NAME}}-${{matrix.label}}-${{steps.branch_name.outputs.PROJECT_VERSION}}_i386.deb
         shell: bash
       - name: Prepare release files on ${{matrix.label}}
         continue-on-error: true
